/*--inicio--> */
var municipioAmazonas = new Array(
  "El Encanto",
  " La Chorrera",
  " La Pedrera",
  " La Victoria",
  " Leticia",
  " Miriti - Parana",
  " Puerto Alegria",
  " Puerto Arica",
  " Puerto Nariño",
  " Puerto Santander",
  " Tarapaca"
);

var municipiosAntioquia = new Array(
  "Abejorral",
  "Abriaqui",
  "Alejandria",
  "Amaga",
  "Amalfi",
  "Andes",
  "Angelopolis",
  "Angostura",
  "Anori",
  "Anza",
  "Apartado",
  "Arboletes",
  "Argelia",
  "Armenia",
  "Barbosa",
  "Bello",
  "Belmira",
  "Betania",
  "Betulia",
  "Briceño",
  "Buritica",
  "Caceres",
  "Caicedo",
  "Caldas",
  "Campamento",
  "Cañasgordas",
  "Caracoli",
  "Caramanta",
  "Carepa",
  "Carmen De Viboral",
  "Carolina",
  "Caucasia",
  "Chigorodo",
  "Cisneros",
  "Ciudad Bolivar",
  "Cocorna",
  "Concepcion",
  "Concordia",
  "Copacabana",
  "Dabeiba",
  "Don Matias",
  "Ebejico",
  "El Bagre",
  "Entrerrios",
  "Envigado",
  "Fredonia",
  "Frontino",
  "Giraldo",
  "Girardota",
  "Gomez Plata",
  "Granada",
  "Guadalupe",
  "Guarne",
  "Guatape",
  "Heliconia",
  "Hispania",
  "Itagui",
  "Ituango",
  "Jardin",
  "Jerico",
  "La Ceja",
  "La Estrella",
  "La Pintada",
  "La Union",
  "Liborina",
  "Maceo",
  "Marinilla",
  "Medellin",
  "Montebello",
  "Murindo",
  "Mutata",
  "Nariño",
  "Nechi",
  "Necocli",
  "Olaya",
  "Peñol",
  "Peque",
  "Pueblorrico",
  "Puerto Berrio",
  "Puerto Nare",
  "Puerto Triunfo",
  "Remedios",
  "Retiro",
  "Rionegro",
  "Sabanalarga",
  "Sabaneta",
  "Salgar",
  "San Andres",
  "San Carlos",
  "San Francisco",
  "San Jeronimo",
  "San Jose De La Montaña",
  "San Juan De Uraba",
  "San Luis",
  "San Pedro",
  "San Pedro De Uraba",
  "San Rafael",
  "San Roque",
  "San Vicente",
  "Santa Barbara",
  "Santa Rosa De Osos",
  "Santafe De Antioquia",
  "Santo Domingo",
  "Santuario",
  "Segovia",
  "Sonson",
  "Sopetran",
  "Tamesis",
  "Taraza",
  "Tarso",
  "Titiribi",
  "Toledo",
  "Turbo",
  "Uramita",
  "Urrao",
  "Valdivia",
  "Valparaiso",
  "Vegachi",
  "Venecia",
  "Vigia Del Fuerte",
  "Yali",
  "Yarumal",
  "Yolombo",
  "Yondo",
  "Zaragoza"
);

var municipiosArauca = new Array(
  "Arauca",
  "Arauquita",
  "Cravo Norte",
  "Fortul",
  "Puerto Rondon",
  "Saravena",
  "Tame"
);

var municipiosArchipielagoDeSanAndres = new Array(
  "Providencia Y Santa Catalina",
  "San Andres"
);

var municipiosAtlantico = new Array(
  "Baranoa",
  "Barranquilla",
  "Campo De La Cruz",
  "Candelaria",
  "Galapa",
  "Juan De Acosta",
  "Luruaco",
  "Malambo",
  "Manati",
  "Palmar De Varela",
  "Piojo",
  "Polonuevo",
  "Ponedera",
  "Puerto Colombia",
  "Repelon",
  "Sabanagrande",
  "Sabanalarga",
  "Santa Lucia",
  "Santo Tomas",
  "Soledad",
  "Suan",
  "Tubara",
  "Usiacuri"
);

var municipiosBogota = new Array("Bogota D.C.");

var municipiosBolivar = new Array(
  "Achi",
  "Altos Del Rosario",
  "Arenal",
  "Arjona",
  "Arroyohondo",
  "Barranco De Loba",
  "Calamar",
  "Cantagallo",
  "Carmen De Bolivar",
  "Cartagena",
  "Cicuco",
  "Clemencia",
  "Cordoba",
  "El Guamo",
  "El Peñon",
  "Hatillo De Loba",
  "Magangue",
  "Mahates",
  "Margarita",
  "Maria La Baja",
  "Mompos",
  "Montecristo",
  "Morales",
  "Pinillos",
  "Regidor",
  "Rio Viejo",
  "San Cristobal",
  "San Estanislao",
  "San Fernando",
  "San Jacinto",
  "San Jacinto Del Cauca",
  "San Juan Nepomuceno",
  "San Martin De Loba",
  "San Pablo",
  "Santa Catalina",
  "Santa Rosa De Lima",
  "Santa Rosa Del Sur",
  "Simiti",
  "Soplaviento",
  "Talaigua Nuevo",
  "Tiquisio",
  "Turbaco",
  "Turbana",
  "Villanueva",
  "Zambrano"
);

var municipiosBoyaca = new Array(
  "Almeida",
  "Aquitania",
  "Arcabuco",
  "Belen",
  "Berbeo",
  "Beteitiva",
  "Boavita",
  "Boyaca",
  "Briceño",
  "Buenavista",
  "Busbanza",
  "Caldas",
  "Campohermoso",
  "Cerinza",
  "Chinavita",
  "Chiquinquira",
  "Chiquiza",
  "Chiscas",
  "Chita",
  "Chitaraque",
  "Chivata",
  "Chivor",
  "Cienega",
  "Combita",
  "Coper",
  "Corrales",
  "Covarachia",
  "Cubara",
  "Cucaita",
  "Cuitiva",
  "Duitama",
  "El Cocuy",
  "El Espino",
  "Firavitoba",
  "Floresta",
  "Gachantiva",
  "Gameza",
  "Garagoa",
  "Guacamayas",
  "Guateque",
  "Guayata",
  "Güican",
  "Iza",
  "Jenesano",
  "Jerico",
  "La Capilla",
  "La Uvita",
  "La Victoria",
  "Labranzagrande",
  "Macanal",
  "Maripi",
  "Miraflores",
  "Mongua",
  "Mongui",
  "Moniquira",
  "Motavita",
  "Muzo",
  "Nobsa",
  "Nuevo Colon",
  "Oicata",
  "Otanche",
  "Pachavita",
  "Paez",
  "Paipa",
  "Pajarito",
  "Panqueba",
  "Pauna",
  "Paya",
  "Paz De Rio",
  "Pesca",
  "Pisba",
  "Puerto Boyaca",
  "Quipama",
  "Ramiriqui",
  "Raquira",
  "Rondon",
  "Saboya",
  "Sachica",
  "Samaca",
  "San Eduardo",
  "San Jose De Pare",
  "San Luis De Gaceno",
  "San Mateo",
  "San Miguel De Sema",
  "San Pablo Borbur",
  "San Rosa Viterbo",
  "Santa Maria",
  "Santa Sofia",
  "Santana",
  "Sativanorte",
  "Sativasur",
  "Siachoque",
  "Soata",
  "Socha",
  "Socota",
  "Sogamoso",
  "Somondoco",
  "Sora",
  "Soraca",
  "Sotaquira",
  "Susacon",
  "Sutamarchan",
  "Sutatenza",
  "Tasco",
  "Tenza",
  "Tibana",
  "Tibasosa",
  "Tinjaca",
  "Tipacoque",
  "Toca",
  "Togüi",
  "Topaga",
  "Tota",
  "Tunja",
  "Tunungua",
  "Turmeque",
  "Tuta",
  "Tutaza",
  "Umbita",
  "Ventaquemada",
  "Villa De Leyva",
  "Viracacha",
  "Zetaquira"
);

var municipiosCaldas = new Array(
  "Aguadas",
  "Anserma",
  "Aranzazu",
  "Belalcazar",
  "Chinchina",
  "Filadelfia",
  "La Dorada",
  "La Merced",
  "Manizales",
  "Manzanares",
  "Marmato",
  "Marquetalia",
  "Marulanda",
  "Neira",
  "Norcasia",
  "Pacora",
  "Palestina",
  "Pensilvania",
  "Riosucio",
  "Risaralda",
  "Salamina",
  "Samana",
  "San Jose",
  "Supia",
  "Victoria",
  "Villamaria",
  "Viterbo"
);

var municipiosCaqueta = new Array(
  "Albania",
  "Cartagena Del Chaira",
  "Currillo",
  "El Doncello",
  "El Paujil",
  "Florencia",
  "La Montañita",
  "Milan",
  "Morelia",
  "Puerto Rico",
  "San Jose Del Fragua",
  "San Vicente Del Caguan",
  "Solano",
  "Solita",
  "Valparaiso",
  "Albania"
);

var municipiosCasanare = new Array(
  "Aguazul",
  "Chameza",
  "Hato Corozal",
  "La Salina",
  "Mani",
  "Monterrey",
  "Nunchia",
  "Orocue",
  "Paz De Ariporo",
  "Pore",
  "Recetor",
  "Sabanalarga",
  "Sacama",
  "San Luis De Palenque",
  "Tamara",
  "Tauramena",
  "Trinidad",
  "Villanueva",
  "Yopal"
);

var municipiosCauca = new Array(
  "Almaguer",
  "Argelia",
  "Balboa",
  "Bolivar",
  "Buenos Aires",
  "Cajibio",
  "Caldono",
  "Caloto",
  "Corinto",
  "El Tambo",
  "Florencia",
  "Guapi",
  "Inza",
  "Jambalo",
  "La Sierra",
  "La Vega",
  "Lopez",
  "Mercaderes",
  "Miranda",
  "Morales",
  "Padilla",
  "Paez",
  "Patia",
  "Piamonte",
  "Piendamo",
  "Popayan",
  "Puerto Tejada",
  "Purace",
  "Rosas",
  "San Sebastian",
  "Santa Rosa",
  "Santander De Quilichao",
  "Silvia",
  "Sotara",
  "Suarez",
  "Sucre",
  "Timbio",
  "Timbiqui",
  "Toribio",
  "Totoro",
  "Villa Rica"
);

var municipiosCesar = new Array(
  "Aguachica",
  "Agustin Codazzi",
  "Astrea",
  "Becerril",
  "Bosconia",
  "Chimichagua",
  "Chiriguana",
  "Curumani",
  "El Copey",
  "El Paso",
  "Gamarra",
  "Gonzalez",
  "La Gloria",
  "La Jagua De Ibirico",
  "La Paz",
  "Manaure",
  "Pailitas",
  "Pelaya",
  "Pueblo Bello",
  "Rio De Oro",
  "San Alberto",
  "San Diego",
  "San Martin",
  "Tamalameque",
  "Valledupar"
);

var municipiosChoco = new Array(
  "Acandi",
  "Alto Baudo",
  "Atrato",
  "Bagado",
  "Bahia Solano",
  "Bajo Baudo",
  "Belen De Bajira",
  "Bojaya",
  "Canton De San Pablo",
  "Carmen Del Darien",
  "Certegui",
  "Condoto",
  "El Carmen De Atrato",
  "El Litoral Del San Juan",
  "Itsmina",
  "Jurado",
  "Lloro",
  "Medio Atrato",
  "Medio Baudo",
  "Medio San Juan",
  "Novita",
  "Nuqui",
  "Quibdo",
  "Rio Frio",
  "Rio Quito",
  "Riosucio",
  "San Jose Del Palmar",
  "Sipi",
  "Tado",
  "Unguia",
  "Union Panamericana"
);

var municipiosCordoba = new Array(
  "Ayapel",
  "Buenavista",
  "Canalete",
  "Cerete",
  "Chima",
  "Chinu",
  "Cienaga De Oro",
  "Cotorra",
  "La Apartada",
  "Lorica",
  "Los Cordobas",
  "Momil",
  "Montelibano",
  "Monteria",
  "Moñitos",
  "Planeta Rica",
  "Pueblo Nuevo",
  "Puerto Escondido",
  "Puerto Libertador",
  "Purisima",
  "Sahagun",
  "San Andres Sotavento",
  "San Antero",
  "San Bernardo Del Viento",
  "San Carlos",
  "San Pelayo",
  "Tierralta",
  "Valencia"
);

var municipiosCundinamarca = new Array(
  "Agua De Dios",
  "Alban",
  "Anapoima",
  "Anolaima",
  "Apulo",
  "Arbelaez",
  "Beltran",
  "Bituima",
  "Bojaca",
  "Cabrera",
  "Cachipay",
  "Cajica",
  "Caparrapi",
  "Caqueza",
  "Carmen De Carupa",
  "Chaguani",
  "Chia",
  "Chipaque",
  "Choachi",
  "Choconta",
  "Cogua",
  "Cota",
  "Cucunuba",
  "El Colegio",
  "El Peñon",
  "El Rosal",
  "Facatativa",
  "Fomeque",
  "Fosca",
  "Funza",
  "Fuquene",
  "Fusagasuga",
  "Gachala",
  "Gachancipa",
  "Gacheta",
  "Gama",
  "Girardot",
  "Granada",
  "Guacheta",
  "Guaduas",
  "Guasca",
  "Guataqui",
  "Guatavita",
  "Guayabal De Siquima",
  "Guayabetal",
  "Gutierrez",
  "Jerusalen",
  "Junin",
  "La Calera",
  "La Mesa",
  "La Palma",
  "La Peña",
  "La Vega",
  "Lenguazaque",
  "Macheta",
  "Madrid",
  "Manta",
  "Medina",
  "Mosquera",
  "Nariño",
  "Nemocon",
  "Nilo",
  "Nimaima",
  "Nocaima",
  "Pacho",
  "Paime",
  "Pandi",
  "Paratebueno",
  "Pasca",
  "Puerto Salgar",
  "Puli",
  "Quebradanegra",
  "Quetame",
  "Quipile",
  "Ricaurte",
  "San Antonio De Tequendama",
  "San Bernardo",
  "San Cayetano",
  "San Francisco",
  "San Juan De Rio Seco",
  "Sasaima",
  "Sesquile",
  "Sibate",
  "Silvania",
  "Simijaca",
  "Soacha",
  "Sopo",
  "Subachoque",
  "Suesca",
  "Supata",
  "Susa",
  "Sutatausa",
  "Tabio",
  "Tausa",
  "Tena",
  "Tenjo",
  "Tibacuy",
  "Tibirita",
  "Tocaima",
  "Tocancipa",
  "Topaipi",
  "Ubala",
  "Ubaque",
  "Ubate",
  "Une",
  "utica",
  "Venecia",
  "Vergara",
  "Viani",
  "Villagomez",
  "Villapinzon",
  "Villeta",
  "Viota",
  "Yacopi",
  "Zipacon",
  "Zipaquira"
);

var municipiosGuainia = new Array(
  "Barranco Mina",
  "Cacahual",
  "Inirida",
  "La Guadalupe",
  "Mapiripan",
  "Morichal",
  "Pana Pana",
  "Puerto Colombia",
  "San Felipe"
);

var municipiosGuainia = new Array(
  "Calamar",
  "El Retorno",
  "Miraflores",
  "San Jose Del Guaviare"
);

var municipiosHuila = new Array(
  "Acevedo",
  "Agrado",
  "Aipe",
  "Algeciras",
  "Altamira",
  "Baraya",
  "Campoalegre",
  "Colombia",
  "Elias",
  "Garzon",
  "Gigante",
  "Guadalupe",
  "Hobo",
  "Iquira",
  "Isnos",
  "La Argentina",
  "La Plata",
  "Nataga",
  "Neiva",
  "Oporapa",
  "Paicol",
  "Palermo",
  "Palestina",
  "Pital",
  "Pitalito",
  "Rivera",
  "Saladoblanco",
  "San Agustin",
  "Santa Maria",
  "Suaza",
  "Tarqui",
  "Tello",
  "Teruel",
  "Tesalia",
  "Timana",
  "Villavieja",
  "Yaguara"
);

var municipiosLaGuajira = new Array(
  "Albania",
  "Barrancas",
  "Dibulla",
  "Distraccion",
  "El Molino",
  "Fonseca",
  "Hatonuevo",
  "La Jagua Del Pilar",
  "Maicao",
  "Manaure",
  "Riohacha",
  "San Juan Del Cesar",
  "Uribia",
  "Urumita",
  "Villanueva"
);

var municipiosMagdalena = new Array(
  "Algarrobo",
  "Aracataca",
  "Ariguani",
  "Cerro San Antonio",
  "Chibolo",
  "Cienaga",
  "Concordia",
  "El Banco",
  "El Piñon",
  "El Reten",
  "Fundacion",
  "Guamal",
  "Nueva Granada",
  "Pedraza",
  "Pijiño Del Carmen",
  "Pivijay",
  "Plato",
  "Pueblo Viejo",
  "Remolino",
  "Sabanas De San Angel",
  "Salamina",
  "San Sebastian De Buenavista",
  "San Zenon",
  "Santa Ana",
  "Santa Barbara De Pinto",
  "Santa Marta",
  "Sitionuevo",
  "Tenerife",
  "Zapayan",
  "Zona Bananera"
);

var municipiosMeta = new Array(
  "Acacias",
  "Barranca De Upia",
  "Cabuyaro",
  "Castilla La Nueva",
  "Cumaral",
  "El Calvario",
  "El Castillo",
  "El Dorado",
  "Fuente De Oro",
  "Granada",
  "Guamal",
  "La Macarena",
  "La Uribe",
  "Lejanias",
  "Mapiripan",
  "Mesetas",
  "Puerto Concordia",
  "Puerto Gaitan",
  "Puerto Lleras",
  "Puerto Lopez",
  "Puerto Rico",
  "Restrepo",
  "San Carlos Guaroa",
  "San Juan De Arama",
  "San Juanito",
  "San Luis De Cubarral",
  "San Martin",
  "Villavicencio",
  "Vista Hermosa"
);

var municipiosNariño = new Array(
  "Alban",
  "Aldana",
  "Ancuya",
  "Arboleda",
  "Barbacoas",
  "Belen",
  "Buesaco",
  "Chachagui",
  "Colon",
  "Consaca",
  "Contadero",
  "Cordoba",
  "Cuaspud",
  "Cumbal",
  "Cumbitara",
  "El Charco",
  "El Peñol",
  "El Rosario",
  "El Tablon De Gomez",
  "El Tambo",
  "Francisco Pizarro",
  "Funes",
  "Guachucal",
  "Guaitarilla",
  "Gualmatan",
  "Iles",
  "Imues",
  "Ipiales",
  "La Cruz",
  "La Florida",
  "La Llanada",
  "La Tola",
  "La Union",
  "Leiva",
  "Linares",
  "Los Andes",
  "Magui",
  "Mallama",
  "Mosquera",
  "Nariño",
  "Olaya Herrera",
  "Ospina",
  "Pasto",
  "Policarpa",
  "Potosi",
  "Providencia",
  "Puerres",
  "Pupiales",
  "Ricaurte",
  "Roberto Payan",
  "Samaniego",
  "San Bernardo",
  "San Lorenzo",
  "San Pablo",
  "San Pedro De Cartago",
  "Sandona",
  "Santa Barbara",
  "Santa Cruz",
  "Sapuyes",
  "Taminango",
  "Tangua",
  "Tumaco",
  "Tuquerres",
  "Yacuanquer"
);

var municipiosNorteDeSantander = new Array(
  "Abrego",
  "Arboledas",
  "Bochalema",
  "Bucarasica",
  "Cachira",
  "Cacota",
  "Chinacota",
  "Chitaga",
  "Convencion",
  "Cucuta",
  "Cucutilla",
  "Durania",
  "El Carmen",
  "El Tarra",
  "El Zulia",
  "Gramalote",
  "Hacari",
  "Herran",
  "La Esperanza",
  "La Playa",
  "Labateca",
  "Los Patios",
  "Lourdes",
  "Mutiscua",
  "Ocaña",
  "Pamplona",
  "Pamplonita",
  "Puerto Santander",
  "Ragonvalia",
  "Salazar",
  "San Calixto",
  "San Cayetano",
  "Santiago",
  "Sardinata",
  "Silos",
  "Teorama",
  "Tibu",
  "Toledo",
  "Villa Caro",
  "Villa Del Rosario"
);

var municipiosPutumayo = new Array(
  "Colon",
  "Mocoa",
  "Orito",
  "Puerto Asis",
  "Puerto Caicedo",
  "Puerto Guzman",
  "Puerto Leguizamo",
  "San Francisco",
  "San Miguel",
  "Santiago",
  "Sibundoy",
  "Valle Del Guamuez",
  "Villa Garzon"
);

var municipiosQuindio = new Array(
  "Armenia",
  "Buenavista",
  "Calarca",
  "Circasia",
  "Cordoba",
  "Filandia",
  "Genova",
  "La Tebaida",
  "Montengro",
  "Pijao",
  "Quimbaya",
  "Salento"
);

var municipiosRisaralda = new Array(
  "Apia",
  "Balboa",
  "Belen De Umbria",
  "Dosquebradas",
  "Guatica",
  "La Celia",
  "La Virginia",
  "Marsella",
  "Mistrato",
  "Pereira",
  "Pueblo Rico",
  "Quinchia",
  "Santa Rosa De Cabal",
  "Santuario"
);

var municipiosSantander = new Array(
  "Aguada",
  "Albania",
  "Aratoca",
  "Barbosa",
  "Barichara",
  "Barrancabermeja",
  "Betulia",
  "Bolivar",
  "Bucaramanga",
  "Cabrera",
  "California",
  "Capitanejo",
  "Carcasi",
  "Cepita",
  "Cerrito",
  "Charala",
  "Charta",
  "Chima",
  "Chipata",
  "Cimitarra",
  "Concepcion",
  "Confines",
  "Contratacion",
  "Coromoro",
  "Curiti",
  "El Carmen De Chucuri",
  "El Guacamayo",
  "El Peñon",
  "El Playon",
  "Encino",
  "Enciso",
  "Florian",
  "Floridablanca",
  "Galan",
  "Gambita",
  "Giron",
  "Guaca",
  "Guadalupe",
  "Guapota",
  "Guavata",
  "Guepsa",
  "Hato",
  "Jesus Maria",
  "Jordan",
  "La Belleza",
  "La Paz",
  "Landazuri",
  "Lebrija",
  "Los Santos",
  "Macaravita",
  "Malaga",
  "Matanza",
  "Mogotes",
  "Molagavita",
  "Ocamonte",
  "Oiba",
  "Onzaga",
  "Palmar",
  "Palmas Del Socorro",
  "Paramo",
  "Piedecuesta",
  "Pinchote",
  "Puente Nacional",
  "Puerto Parra",
  "Puerto Wilches",
  "Rionegro",
  "Sabana De Torres",
  "San Andres",
  "San Benito",
  "San Gil",
  "San Joaquin",
  "San Jose De Miranda",
  "San Miguel",
  "San Vicente De Chucuri",
  "Santa Barbara",
  "Santa Helena Del Opon",
  "Simacota",
  "Socorro",
  "Suaita",
  "Sucre",
  "Surata",
  "Tona",
  "Valle De San Jose",
  "Velez",
  "Vetas",
  "Villanueva",
  "Zapatoca"
);

var municipiosSucre = new Array(
  "Buenavista",
  "Caimito",
  "Chalan",
  "Coloso",
  "Corozal",
  "Coveñas",
  "El Roble",
  "Galeras",
  "Guaranda",
  "La Union",
  "Los Palmitos",
  "Majagual",
  "Morroa",
  "Ovejas",
  "Palmito",
  "Sampues",
  "San Benito Abad",
  "San Juan Betulia",
  "San Marcos",
  "San Onofre",
  "San Pedro",
  "Santiago De Tolu",
  "Since",
  "Sincelejo",
  "Sucre",
  "Tolu Viejo"
);

var municipiosTolima = new Array(
  "Alpujarra",
  "Alvarado",
  "Ambalema",
  "Anzoategui",
  "Armero",
  "Ataco",
  "Cajamarca",
  "Carmen De Apicala",
  "Casabianca",
  "Chaparral",
  "Coello",
  "Coyaima",
  "Cunday",
  "Dolores",
  "Espinal",
  "Falan",
  "Flandes",
  "Fresno",
  "Guamo",
  "Herveo",
  "Honda",
  "Ibague",
  "Icononzo",
  "Lerida",
  "Libano",
  "Mariquita",
  "Melgar",
  "Murillo",
  "Natagaima",
  "Ortega",
  "Palocabildo",
  "Piedras",
  "Planadas",
  "Prado",
  "Purificacion",
  "Rioblanco",
  "Roncesvalles",
  "Rovira",
  "Saldaña",
  "San Antonio",
  "San Luis",
  "Santa Isabel",
  "Suarez",
  "Valle De San Juan",
  "Venadillo",
  "Villahermosa",
  "Villarrica"
);

var municipiosValleDelCauca = new Array(
  "Alcala",
  "Andalucia",
  "Ansermanuevo",
  "Argelia",
  "Bolivar",
  "Buenaventura",
  "Buga",
  "Bugalagrande",
  "Caicedonia",
  "Cali",
  "Calima",
  "Candelaria",
  "Cartago",
  "Dagua",
  "El aguila",
  "El Cairo",
  "El Cerrito",
  "El Dovio",
  "Florida",
  "Ginebra",
  "Guacari",
  "Jamundi",
  "La Cumbre",
  "La Union",
  "La Victoria",
  "Obando",
  "Palmira",
  "Pradera",
  "Restrepo",
  "Riofrio",
  "Roldanillo",
  "San Pedro",
  "Sevilla",
  "Toro",
  "Trujillo",
  "Tulua",
  "Ulloa",
  "Versalles",
  "Vijes",
  "Yotoco",
  "Yumbo",
  "Zarzal"
);

var municipiosVaupes = new Array(
  "Caruru",
  "Mitu",
  "Pacoa",
  "Papunahua",
  "Taraira",
  "Yavarate"
);

var municipiosVichada = new Array(
  "Cumaribo",
  "La Primavera",
  "Puerto Carreño",
  "Santa Rosalia"
);

function crearMunicipio() {
  // tomamos el valor del select  con el departamento elegido
  var departamentoSeleccionado = document.getElementById("departments").value;
  alert(departamentoSeleccionado);

  // verifica si el departamento esta definido
  if (departamentoSeleccionado != 0) {
    // coloco los municipios del departamento correspondiente
    municipios = eval(departamentoSeleccionado);
    alert(municipios);
    num_municipios = municipios.length;
    alert(num_municipios);
    document.personalData.municipalityList.length = num_municipios;

    // introduzco en el select cada municipio del array
    for (i = 0; i < num_municipios; i++) {
      document.personalData.municipalityList.options[i].value = municipios[i];
      document.personalData.municipalityList.options[i].text = municipios[i];
    }
  } else {
    document.personalData.municipalityList.length = 1;
    document.personalData.municipalityList.options[0].value = " ";
    document.personalData.municipalityList.options[0].text = "sin asignar";
  }
}

function calcularEdad(birthdate) {
  var fechaNacimiento = document.getElementById("birthdate").value;
  var edad = document.getElementById("age").value;
  console.log(fechaNacimiento + edad);

  // var hoy = new Date();
  // var edad = hoy.getFullYear() - fechaNacimiento.getFullYear();
  // var mes = hoy.getMonth() - fechaNacimiento.getMonth();

  // if (mes < 0 || (mes === 0 && hoy.getDate() < fechaNacimiento.getDate())) {
  //   edad--;
  // }

  // return edad;
}
